README.md

Add checkmark for documentation

---

README.md
src/styles/mdc.scss

Fix typo in README

---

package.json

Improve social

---

README.md
public/global.css
src/App.svelte
src/components/components.module.js
src/components/switch/Component.svelte
src/components/switch/README.md

Something like [this](https://material.io/design/components/selection-controls.html#switches).

Create a switch

---

README.md

Add a component-status section

---

README.md
package.json

Keep bundle.css

---

README.md

Add a credits section to the README

---

README.md

Add support for others

---

src/App.svelte
src/components/button/Component.svelte
src/components/button/README.md

Give UIButton an outlined prop

---

src/components/input/Component.svelte

Make margin = 0

---

.gitignore
README.md
package.json
src/App.svelte
src/components/card/Component.svelte
src/components/card/README.md
src/components/components.module.js
src/components/ripple/README.md
src/components/ripple/Ripple.svelte

Card Component

---

src/App.svelte
src/components/card/Component.svelte
src/components/card/README.md

Add an outlined prop

---

src/App.svelte
src/components/card/Component.svelte
src/components/card/README.md

Animate shadows

---

public/global.css
src/components/card/Component.svelte
src/components/card/README.md

Card colors

---

src/App.svelte
src/components/card/Component.svelte
src/components/card/README.md

Card border options

---

README.md
src/App.svelte
src/components/checkbox/Component.svelte
src/components/components.module.js

Checkbox basics

---

src/components/checkbox/Component.svelte
src/components/checkbox/README.md

Checkbox documentation

---

src/components/icon-button/README.md

Fix broken page

---

src/App.svelte
src/components/card/Component.svelte

Make href work on card

---

src/components/checkbox/LabelWrapper.svelte

Move event dispatcher to inline element

---

src/components/button/Component.svelte

Center button
